### ISSUE TITLE
ATEM Constellation 8k not working properly

### ISSUE THREAD

**Issue by yannisgu** [SuperFlyTV/SuperConductor#142]
**Describe the bug**

I'm trying to make SuperConductor to work with the ATEM Constallation 8k. 

<img width="525" alt="Screenshot 2023-05-02 at 14 36 55" src="https://user-images.githubusercontent.com/1180984/235667846-4601a1ef-f630-4524-99db-14283e4a1004.png">

I can connect to the ATEM, but when I connect, the whole state of the ATEM is reset (e.g. all SuperSource or Upstream Keyers are reseted, all program inputs are set to BLK) and also I don't get any ressource in the rundown view:

<img width="367" alt="Screenshot 2023-05-02 at 14 38 40" src="https://user-images.githubusercontent.com/1180984/235668265-8ad1fcf2-3020-42e8-8a11-c8ca69216d3a.png">

I also tried to refresh the available resources but don't get anything.

**To Reproduce**

1. Connect SuperConductor with ATEM Constellation 8k
2. Check ATEM Configuration, which is completly
3. Go to the Rundown und check the right "Ressources" Sidebar which is completly empty

**Expected behavior**
- ATEM is not reseted when connecting to ATEM or starting SuperConductor
- Camera Inputs etc.. are visible in the resources view

**Screenshots**
Added to the desscription

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
-

**Comment by yannisgu** [comment]
I now restarted SuperConductor couple of times and observed different behaviours:
- Sometimes it rested the ATEM and no resources visible
- Once it didn't reset the ATEM but also no resources visible
- Once it rested the ATEM, but loaded the resources

**Comment by nytamin** [comment]
Thanks for the report!

I don't have a Constellation 8k readily available for testing, so first we need to figure out if your issues are unique to that or if they apply to all/most of the ATEM.

**Regarding the whole-ATEM-reset issue**

This is a known problem, and is addressed in this issue, 
[Feature request: ATEM "takeover" ON-OFF ](https://github.com/SuperFlyTV/SuperConductor/issues/122).

**Regarding the missing resources**

This might be a tough nut to crack without hands-on fiddling with the Constellation.
If you would be able to help troubleshooting this, that would help a lot!

If you where to clone the repo and start it up in dev-mode (`npm run start`) and add a few `console.log`'s, you might be able to figure out what the issue is.

The resources are fetched here, https://github.com/SuperFlyTV/SuperConductor/blob/84640368b08dda223588ae4f77df15f27f1dd18f/shared/packages/tsr-bridge/src/sideload/Atem.ts#L51 so the problem is probably somewhere in the vicinity of there.

**Comment by x3rud** [comment]
Hello there,

I made some test, the TRS get stuck on the initialization of the device

`superconductor: [1] 2023-05-09T07:23:18.232Z [electron] info: TSR Initializing device sLKrC44P (443) of type ATEM...
superconductor: [1] 2023-05-09T07:23:23.769Z [electron] error: TSR device error: Method "init()" aborted due to: Child process "Child_ instance_2427_6_sLKrC44P" was closed, Error: Method "init()" aborted due to: Child process "Child_ instance_2427_6_sLKrC44P" was closed
superconductor: [1]     at C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\manager.js:949:27
superconductor: [1]     at Array.forEach (<anonymous>)
superconductor: [1]     at ThreadedClassManagerClassInternal.rejectChildMethods (C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\manager.js:947:36)        
superconductor: [1]     at ThreadedClassManagerClassInternal._childHasCrashed (C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\manager.js:673:14)
superconductor: [1]     at FakeProcess.<anonymous> (C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\manager.js:766:22)
superconductor: [1]     at FakeProcess.emit (C:\Users\X\Documents\SuperConductor-master\node_modules\eventemitter3\index.js:201:33)
superconductor: [1]     at FakeProcess.kill (C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\workerPlatform\fakeWorker.js:16:14)
superconductor: [1]     at C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\manager.js:940:39
superconductor: [1]     at new Promise (<anonymous>)
superconductor: [1]     at ThreadedClassManagerClassInternal.killChild (C:\Users\X\Documents\SuperConductor-master\node_modules\threadedclass\dist\parent-process\manager.js:881:16)
superconductor: [1] 2023-05-09T07:23:23.770Z [electron] info: TSR Initializing device sLKrC44P (3940) of type ATEM...
superconductor: [1] 2023-05-09T07:23:23.843Z [electron] info: TSR Device sLKrC44P (3940) initialized!`

If I run the app again in dev mode the resources of the atem are available on the view.

I've just open up the code now I'll going to search the problem.

**Comment by Julusian** [comment]
@nytamin using https://github.com/LibAtem/AtemUtils/tree/master/AtemMock with one of the data files from https://github.com/nrkno/sofie-atem-connection/tree/master/src/__tests__/connection will give you enough of a constellation to make the atem library (and official software) think its connected to a constelllation 8k, or whatever model you choose.

Or if that doesnt reproduce it, there is a tool https://builds.julusian.dev/atem/ to generate one of those data files from an atem, which would be useful to add as a test case if something is broken in the connection library
