### ISSUE TITLE
Windows 10 issue. No GUI loaded/Black screen.

### ISSUE THREAD

**Issue by nyok92** [SuperFlyTV/SuperConductor#15]
**Describe the bug**
Can't load GUI, Reload or force reload doesn't work. Can access Preferences menu

**To Reproduce**
Installed last version 0.5.0
Same issue with previous versions

**Expected behavior**
Working correctly

**Desktop (please complete the following information):**
 - windows 10
 - version 21H2

**Additional context**
From dev console : 

Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
You might need to use a local HTTP server (instead of file://): https://reactjs.org/link/react-devtools-faq
App.tsx:102 triggerSendAll
PartView.tsx:134 Uncaught TypeError: Cannot read properties of undefined (reading 'references')
    at PartView.tsx:134
    at mountMemo (react-dom.development.js:15846)
    at Object.useMemo (react-dom.development.js:16219)
    at useMemo (react.development.js:1532)
    at PartView (PartView.tsx:125)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
react-dom.development.js:20085 The above error occurred in the <PartView> component:

    at PartView (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:225915:24)
    at div
    at div
    at div
    at GroupView (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:225234:20)
    at div
    at RundownView (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:227011:23)
    at div
    at div
    at observerComponent (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:93900:73)
    at SnackbarProvider (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:123338:24)
    at InnerThemeProvider (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:62264:70)
    at ThemeProvider (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:61975:5)
    at ThemeProvider (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:62284:5)
    at DndProvider (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:126398:23)
    at ContextWrapper (file:///C:/Users/nicol/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:231531:37)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
PartView.tsx:134 Uncaught TypeError: Cannot read properties of undefined (reading 'references')
    at PartView.tsx:134
    at mountMemo (react-dom.development.js:15846)
    at Object.useMemo (react-dom.development.js:16219)
    at useMemo (react.development.js:1532)
    at PartView (PartView.tsx:125)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)

**Comment by alvancamp** [comment]
Do you have reproduction steps for this bug? It would help us to track it down.

In the meantime, you can reset your SuperConductor state by deleting the `SuperConductor` folder within your Documents folder. Do this while SuperConductor isn't running. This should let you use the program again.

**Comment by nyok92** [comment]
thanks, it worked
