### ISSUE TITLE
After Deleting the First Item in the Group UI Disaappers

### ISSUE THREAD

**Issue by ievgeniilarin** [SuperFlyTV/SuperConductor#24]
After deleting the first item in a part UI is replaced with a black screen. I was using the vMix integration.

Rebooting and reinstalling don't help. Reloading and Force Reloading don't help.

Windows 10.

![2022-04-13 03_14_32-Window](https://user-images.githubusercontent.com/797871/163074724-d69e647f-0c84-4a42-94e7-d2f4046b72a7.png)

**Comment by ievgeniilarin** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'references')
    at renderer.js:231517
    at mountMemo (renderer.js:147650)
    at Object.useMemo (renderer.js:148023)
    at useMemo (renderer.js:219454)
    at PartView (renderer.js:231510)
    at renderer.js:95905
    at renderer.js:96210
    at trackDerivedFunction (renderer.js:98637)
    at Reaction.track (renderer.js:99223)
    at useObserver (renderer.js:96208)

react-dom.development.js:20085 The above error occurred in the <PartView> component:

    at observerComponent (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:95905:73)
    at div
    at observerComponent (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:95905:73)
    at div
    at observerComponent (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:95905:73)
    at div
    at div
    at observerComponent (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:95905:73)
    at SnackbarProvider (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:125343:24)
    at InnerThemeProvider (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:62331:70)
    at ThemeProvider (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:62042:5)
    at ThemeProvider (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:62351:5)
    at DndProvider (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:128568:23)
    at ContextWrapper (file:///C:/Users/ievge/AppData/Local/Programs/superconductor/resources/app.asar/dist/renderer.js:237811:39)

Uncaught TypeError: Cannot read properties of undefined (reading 'references')
    at renderer.js:231517
    at mountMemo (renderer.js:147650)
    at Object.useMemo (renderer.js:148023)
    at useMemo (renderer.js:219454)
    at PartView (renderer.js:231510)
    at renderer.js:95905
    at renderer.js:96210
    at trackDerivedFunction (renderer.js:98637)
    at Reaction.track (renderer.js:99223)
    at useObserver (renderer.js:96208)

**Comment by alvancamp** [comment]
Hi @ievgeniilarin! Thanks for this bug report.

We're aware of the issue and working on a fix. In the meantime, you can restore the UI by performing the following procedure:

1. Close SuperConductor if it is running.
2. Locate the `Documents/SuperConductor` folder and delete it.
3. Re-open SuperConductor.

**Comment by ievgeniilarin** [comment]
Hi @alvancamp!

Thanks. It worked.

**Comment by nytamin** [comment]
This should be fixed in the latest version, 0.7.2
