### ISSUE TITLE
OSX not starting because of JavaScript error

### ISSUE THREAD

**Issue by KorneB** [SuperFlyTV/SuperConductor#25]
Trying to start the SuperConductor application in OSX result in a JavaScript Error:

Uncaught Exception:
Error: dlopen(/var/folders/lm/7dvkmym16gz_qy_xb4yks8kw0000gn/T/.tv.superfly.superconductor.oCZdF7, 0x0001): tried: '/var/folders/lm/7dvkmym16gz_qy_xb4yks8kw0000gn/T/.tv.superfly.superconductor.oCZdF7' (code signature in <AB90D580-44E6-3C7B-9FEB-810B43A5F7DD> '/private/var/folders/lm/7dvkmym16gz_qy_xb4yks8kw0000gn/T/.tv.superfly.superconductor.oCZdF7' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/.tv.superfly.superconductor.oCZdF7' (no such file), '/private/var/folders/lm/7dvkmym16gz_qy_xb4yks8kw0000gn/T/.tv.superfly.superconductor.oCZdF7' (code signature in <AB90D580-44E6-3C7B-9FEB-810B43A5F7DD> '/private/var/folders/lm/7dvkmym16gz_qy_xb4yks8kw0000gn/T/.tv.superfly.superconductor.oCZdF7' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/.tv.superfly.superconductor.oCZdF7' (no such file)
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at bindings (/Applications/SuperConductor.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
at loadBinding (/Applications/SuperConductor.app/Contents/Resources/app.asar/node_modules/node-hid/nodehid.js:25:42)

Keep up the good work!

**Comment by alvancamp** [comment]
@KorneB can you try the build linked here?: https://github.com/SuperFlyTV/SuperConductor/issues/14#issuecomment-1093107028

**Comment by KorneB** [comment]
Yes, that one is working. When i try to connect to vMix, can i use the same port that for instance companion uses (8099)?

**Comment by alvancamp** [comment]
I'm not sure I understand the question. By default, VMix uses port 8088 for its HTTP API. You can look in your VMix settings to see which port number it has been configured to use and then use that same number in SuperConductor.

**Comment by KorneB** [comment]
Ah, now i see. First i have to create the bridge and then the connection. It's working!!
