### ISSUE TITLE
When first added, ATEM devices fail to retrieve resources

### ISSUE THREAD

**Issue by anarcho-loneliness** [SuperFlyTV/SuperConductor#64]
**Describe the bug**
When an ATEM device is first added, a threadedclass error is logged and the sideload connection is not created, resulting in no resources being populated. Closing and reopening SuperConductor results in no errors being logged and things working as expected.

**To Reproduce**
1. Remove your ATEM device, if it exists
2. Add your ATEM device
3. Observe that even though the ATEM is connected to and shows an accurate status, no resources are displayed
4. Check the TSR-Bridge logs and see something like the log below.
5. Restart SuperConductor and observe that no error is logged and the resources are populated
```
2022-08-23T22:42:37.628Z [electron] info: TSR Initializing device dZchA37X (1280) of type ATEM...
2022-08-23T22:42:41.316Z [electron] error: Method aborted due to: Child process "Child_ instance_4865_2_dZchA37X" was closedMethod aborted due to: Child process "Child_ instance_4865_2_dZchA37X" was closed, Error: Method aborted due to: Child process "Child_ instance_4865_2_dZchA37X" was closed
    at C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\manager.js:773:27
    at Array.forEach (<anonymous>)
    at ThreadedClassManagerClassInternal.rejectChildMethods (C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\manager.js:771:36)
    at ThreadedClassManagerClassInternal._childHasCrashed (C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\manager.js:569:14)
    at FakeProcess.<anonymous> (C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\manager.js:620:22)
    at FakeProcess.emit (C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\eventemitter3\index.js:201:33)
    at FakeProcess.kill (C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\workerPlatform\fakeWorker.js:15:14)
    at C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\manager.js:764:39
    at new Promise (<anonymous>)
    at ThreadedClassManagerClassInternal.killChild (C:\Users\vanca\AppData\Local\Programs\superconductor\resources\app.asar\node_modules\threadedclass\dist\parent-process\manager.js:727:16)
2022-08-23T22:42:41.317Z [electron] info: TSR Initializing device dZchA37X (9834) of type ATEM...
2022-08-23T22:42:41.452Z [electron] info: TSR Device dZchA37X (9834) initialized!
```

**Expected behavior**
ATEM resources should appear when a device is first added and connected to.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro
 - Version 0.8.4

**Additional context**
Tested with an ATEM 2 M/E Production Studio 4K running software version 8.6.4. Another user also tested it with a 1 M/E on an unknown version.

**Comment by nytamin** [comment]
Note to self: We should check if this is still an issue in the latest alpha ([Release v0.12.0-alpha.3](https://github.com/SuperFlyTV/SuperConductor/releases/tag/v0.12.0-alpha.3)) since that uses an updated version of TSR.
